import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import * as os from 'node:os';
import { safeWrite } from '../src/writer/safe-write.js';

describe('Safe File Writer', () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'o2p-test-'));
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  it('creates new generated file with hash header', async () => {
    const filePath = path.join(tempDir, 'test.ts');
    const outcome = await safeWrite({
      absPath: filePath,
      path: 'test.ts',
      content: 'export const value = 42;\n',
      kind: 'generated',
    });

    expect(outcome.status).toBe('created');
    const written = await fs.readFile(filePath, 'utf8');
    expect(written).toContain('// auto-generated by openapi-to-production. DO NOT EDIT. o2p-hash:');
    expect(written).toContain('export const value = 42;');
  });

  it('detects unchanged file on subsequent write', async () => {
    const filePath = path.join(tempDir, 'test.ts');
    await safeWrite({
      absPath: filePath,
      path: 'test.ts',
      content: 'export const value = 42;\n',
      kind: 'generated',
    });

    const second = await safeWrite({
      absPath: filePath,
      path: 'test.ts',
      content: 'export const value = 42;\n',
      kind: 'generated',
    });

    expect(second.status).toBe('unchanged');
  });

  it('detects user modifications and prevents overwrite by default', async () => {
    const filePath = path.join(tempDir, 'test.ts');
    await safeWrite({
      absPath: filePath,
      path: 'test.ts',
      content: 'export const value = 42;\n',
      kind: 'generated',
    });

    // User modifies file
    const original = await fs.readFile(filePath, 'utf8');
    const modified = original + '\n// user added custom code';
    await fs.writeFile(filePath, modified, 'utf8');

    // Attempt regeneration
    const regen = await safeWrite({
      absPath: filePath,
      path: 'test.ts',
      content: 'export const value = 99;\n',
      kind: 'generated',
    });

    expect(regen.status).toBe('conflict');
    expect(regen.reason).toBe('user-modified');
  });

  it('skips existing scaffold files', async () => {
    const filePath = path.join(tempDir, 'controller.cs');
    const first = await safeWrite({
      absPath: filePath,
      path: 'controller.cs',
      content: 'public class Controller {}',
      kind: 'scaffold',
    });
    expect(first.status).toBe('created');

    const second = await safeWrite({
      absPath: filePath,
      path: 'controller.cs',
      content: 'public class NewController {}',
      kind: 'scaffold',
    });
    expect(second.status).toBe('skipped-scaffold');
  });
});
