import { createHash } from 'node:crypto';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { AbsGeneratedFile, WriteOutcome } from '../types/index.js';

const header = (hash: string, ext: string) => {
  const line = `auto-generated by openapi-to-production. DO NOT EDIT. o2p-hash:${hash}`;
  return ext === '.cs' || ext === '.ts' || ext === '.tsx' ? `// ${line}\n` : `# ${line}\n`;
};

const sha = (s: string) => createHash('sha256').update(s).digest('hex').slice(0, 16);

export async function safeWrite(
  file: AbsGeneratedFile,
  opts: { force?: boolean } = {}
): Promise<WriteOutcome> {
  const ext = path.extname(file.absPath);
  const exists = await fileExists(file.absPath);

  // 1. Scaffold files: written once, never overwritten unless forced
  if (file.kind === 'scaffold') {
    if (exists && !opts.force) {
      return { status: 'skipped-scaffold', path: file.absPath };
    }
    await fs.mkdir(path.dirname(file.absPath), { recursive: true });
    await fs.writeFile(file.absPath, file.content, 'utf8');
    return { status: 'created', path: file.absPath };
  }

  // 2. Generated files: protected with hash headers
  const body = file.content;
  const hash = sha(body);
  const next = header(hash, ext) + body;

  if (!exists) {
    await fs.mkdir(path.dirname(file.absPath), { recursive: true });
    await fs.writeFile(file.absPath, next, 'utf8');
    return { status: 'created', path: file.absPath };
  }

  const current = await fs.readFile(file.absPath, 'utf8');
  const firstLine = current.split('\n')[0] || '';
  const m = /o2p-hash:([a-f0-9]{16})/.exec(firstLine);

  if (!m) {
    if (opts.force) {
      await fs.writeFile(file.absPath, next, 'utf8');
      return { status: 'overwritten', path: file.absPath };
    }
    return { status: 'conflict', path: file.absPath, reason: 'no-header' };
  }

  const currentBody = current.slice(current.indexOf('\n') + 1);
  const userEdited = sha(currentBody) !== m[1];
  if (userEdited && !opts.force) {
    return { status: 'conflict', path: file.absPath, reason: 'user-modified' };
  }

  if (current === next) {
    return { status: 'unchanged', path: file.absPath };
  }

  await fs.writeFile(file.absPath, next, 'utf8');
  return { status: 'updated', path: file.absPath };
}

export async function writeAll(
  files: AbsGeneratedFile[],
  opts: { force?: boolean } = {}
): Promise<{ written: WriteOutcome[]; conflicts: WriteOutcome[]; skipped: WriteOutcome[] }> {
  const written: WriteOutcome[] = [];
  const conflicts: WriteOutcome[] = [];
  const skipped: WriteOutcome[] = [];

  for (const file of files) {
    const outcome = await safeWrite(file, opts);
    if (outcome.status === 'conflict') {
      conflicts.push(outcome);
    } else if (outcome.status === 'skipped-scaffold' || outcome.status === 'unchanged') {
      skipped.push(outcome);
    } else {
      written.push(outcome);
    }
  }

  return { written, conflicts, skipped };
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}
